/**
 * Command: pp-agency new-project <name>
 *
 * Creates a new Power Platform project with boilerplate documentation.
 */

import * as path from 'node:path';
import { Command } from 'commander';
import { ProjectType, type ProjectConfig } from '../lib/project-types.js';
import { ensureDir, writeFile, logInfo } from '../lib/file-utils.js';
import { projectBriefTemplate } from '../lib/templates.js';

// ---------------------------------------------------------------------------
// Chalk safe-import
// ---------------------------------------------------------------------------
let chalk: typeof import('chalk').default | undefined;
try {
  const chalkMod = await import('chalk');
  chalk = chalkMod.default;
} catch {
  chalk = undefined;
}

const _cyan = (s: string): string => (chalk ? chalk.cyan(s) : s);
const _green = (s: string): string => (chalk ? chalk.green(s) : s);
const _yellow = (s: string): string => (chalk ? chalk.yellow(s) : s);

// ---------------------------------------------------------------------------
// Options interface
// ---------------------------------------------------------------------------
interface NewProjectOptions {
  type?: string;
  client?: string;
  output?: string;
  verbose?: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function resolveProjectType(type?: string): ProjectType {
  if (!type) return ProjectType.CanvasApp;

  const normalized = type.toLowerCase().replace(/_/g, '-');

  const typeMap: Record<string, ProjectType> = {
    'canvas-app': ProjectType.CanvasApp,
    'model-driven': ProjectType.ModelDriven,
    'power-pages': ProjectType.PowerPages,
    'integration': ProjectType.Integration,
    'copilot': ProjectType.Copilot,
    'full-solution': ProjectType.FullSolution,
    'canvas': ProjectType.CanvasApp,
    'model': ProjectType.ModelDriven,
    'pages': ProjectType.PowerPages,
  };

  return typeMap[normalized] ?? ProjectType.CanvasApp;
}

function generateDiscoveryNotes(config: ProjectConfig): string {
  const date = new Date().toISOString().split('T')[0];

  return `---
title: "${config.name} — Discovery Notes"
project: "${config.name}"
client: "${config.client}"
date: "${date}"
version: "1.0.0"
---

# ${config.name} — Discovery Notes

## Session Details

- **Date:** ${date}
- **Client:** ${config.client}
- **Project Type:** ${config.type}
- **Facilitator:** [Your name]

## Attendees

| Name | Role | Organization |
| ---- | ---- | ------------ |
|      |      |              |

## Current State

> Document the client's current processes, pain points, and systems.

## Requirements Gathering

### Must Have
- [ ] Requirement 1
- [ ] Requirement 2

### Should Have
- [ ] Requirement 3

### Could Have
- [ ] Nice-to-have feature

### Won't Have (this phase)
- [ ] Out of scope item

## Systems & Integrations

| System | Type | Integration Method | Notes |
| ------ | ---- | ----------------- | ----- |
|        |      |                   |       |

## Data & Reporting

> Document data sources, volume estimates, and reporting needs.

## Decisions & Actions

| Item | Owner | Due Date | Status |
| ---- | ----- | -------- | ------ |
|      |       |          |        |

## Risk Notes

> Capture any early risk indicators from the discovery session.

---

_Generated by pp-agency_
`;
}

// ---------------------------------------------------------------------------
// Command registration
// ---------------------------------------------------------------------------

export function registerNewProjectCommand(program: Command): void {
  program
    .command('new-project <name>')
    .description('Create a new Power Platform project with boilerplate documentation')
    .option('-t, --type <type>', 'Project type (canvas-app, model-driven, power-pages, integration, copilot, full-solution)')
    .option('-c, --client <client>', 'Client or organization name')
    .option('-o, --output <dir>', 'Output directory', process.cwd())
    .action(async (name: string, options: NewProjectOptions) => {
      try {
        console.log(_cyan(`\nCreating new project: "${name}"\n`));

        const projectType = resolveProjectType(options.type);
        const client = options.client ?? 'Unknown Client';
        const outputDir = path.resolve(options.output ?? process.cwd());

        const config: ProjectConfig = {
          name,
          type: projectType,
          client,
          description: `${name} — A Power Platform ${projectType} project for ${client}.`,
          createdAt: new Date().toISOString(),
          version: '1.0.0',
        };

        if (options.verbose) {
          logInfo(`Type resolved to: ${projectType}`);
          logInfo(`Output directory: ${outputDir}`);
        }

        // Create project directory
        const projectDir = path.join(outputDir, name.toLowerCase().replace(/\s+/g, '-'));
        ensureDir(projectDir);
        ensureDir(path.join(projectDir, 'checklists'));
        ensureDir(path.join(projectDir, 'agents'));
        ensureDir(path.join(projectDir, 'docs'));

        // Generate project-brief.md
        const briefPath = path.join(projectDir, 'project-brief.md');
        const briefContent = projectBriefTemplate(config);
        writeFile(briefPath, briefContent);

        // Generate discovery-notes.md
        const notesPath = path.join(projectDir, 'discovery-notes.md');
        const notesContent = generateDiscoveryNotes(config);
        writeFile(notesPath, notesContent);

        console.log(_green(`\nProject "${name}" created successfully!\n`));
        console.log(_yellow('Created files:'));
        console.log(`  ${briefPath}`);
        console.log(`  ${notesPath}`);
        console.log(`\nNext steps:`);
        console.log(`  1. Review ${briefPath}`);
        console.log(`  2. Run: pp-agency discovery`);
        console.log(`  3. Run: pp-agency generate-prd --project "${name}"\n`);
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        console.error(`Error creating project: ${message}`);
        process.exit(1);
      }
    });
}
