/**
 * Template engine for generating Power Platform project documents.
 *
 * Templates use {{variableName}} syntax for variable substitution.
 * Built-in templates are provided for all standard document types.
 */

import {
  type ProjectConfig,
  AgentType,
  ProjectType,
} from './project-types.js';
import {
  frontmatter,
  heading,
  table,
  codeBlock,
  checklist,
  horizontalRule,
  bold,
} from './markdown-utils.js';

// ---------------------------------------------------------------------------
// Template engine
// ---------------------------------------------------------------------------

/**
 * Replace {{key}} placeholders in a template string with values from `data`.
 * Keys that are not found in `data` are left untouched.
 */
export function renderTemplate(template: string, data: Record<string, unknown>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_match, key: string) => {
    if (key in data && data[key] !== undefined && data[key] !== null) {
      return String(data[key]);
    }
    return `{{${key}}}`;
  });
}

// ---------------------------------------------------------------------------
// Template data builders
// ---------------------------------------------------------------------------

/**
 * Build the common variable map used by most templates from a ProjectConfig.
 */
export function buildTemplateData(config: ProjectConfig): Record<string, unknown> {
  return {
    projectName: config.name,
    projectType: config.type,
    projectTypeLabel: getProjectTypeLabel(config.type),
    client: config.client,
    description: config.description,
    createdAt: config.createdAt,
    version: config.version,
    date: new Date().toISOString().split('T')[0],
    year: new Date().getFullYear(),
  };
}

/**
 * Get a human-readable label for a project type.
 */
export function getProjectTypeLabel(type: ProjectType): string {
  const labels: Record<ProjectType, string> = {
    [ProjectType.CanvasApp]: 'Canvas App',
    [ProjectType.ModelDriven]: 'Model-Driven App',
    [ProjectType.PowerPages]: 'Power Pages',
    [ProjectType.Integration]: 'Integration',
    [ProjectType.Copilot]: 'Copilot / AI',
    [ProjectType.FullSolution]: 'Full Solution',
  };
  return labels[type] ?? 'Unknown';
}

/**
 * Get a human-readable label for an agent type.
 */
export function getAgentTypeLabel(type: AgentType): string {
  const labels: Record<AgentType, string> = {
    [AgentType.Architect]: 'Solution Architect',
    [AgentType.DataModeler]: 'Data Modeler',
    [AgentType.Developer]: 'Power Platform Developer',
    [AgentType.Tester]: 'QA / Test Engineer',
    [AgentType.AlmEngineer]: 'ALM Engineer',
    [AgentType.SecurityAdmin]: 'Security Administrator',
  };
  return labels[type] ?? 'Unknown Agent';
}

// ---------------------------------------------------------------------------
// Built-in templates
// ---------------------------------------------------------------------------

/**
 * Generate a project brief document.
 */
export function projectBriefTemplate(config: ProjectConfig): string {
  const vars = buildTemplateData(config);

  const fm = frontmatter({
    title: `${config.name} — Project Brief`,
    project: config.name,
    client: config.client,
    type: config.type,
    date: vars.date,
    version: config.version,
  });

  const body = [
    heading(`${config.name} — Project Brief`, 1),
    heading('Overview', 2),
    `${vars.description as string}\n`,
    heading('Client', 2),
    `- **Name:** ${vars.client as string}`,
    `- **Project Type:** ${vars.projectTypeLabel as string}`,
    `- **Created:** ${vars.createdAt as string}\n`,
    heading('Scope', 2),
    '> Define the scope of this engagement. What is included and what is out of scope?\n',
    heading('Objectives', 2),
    checklist([
      'Primary business objective defined',
      'Success criteria documented',
      'Key stakeholders identified',
      'Timeline constraints noted',
    ]),
    heading('Deliverables', 2),
    checklist([
      'Discovery report',
      'Product requirements document (PRD)',
      'Solution design document',
      'Configured Power Platform solution',
      'Test plan and results',
      'Training materials',
      'Support handover documentation',
    ]),
    heading('Assumptions & Constraints', 2),
    checklist([
      'Licensing assumptions documented',
      'Environment strategy agreed',
      'Data residency requirements confirmed',
      'Integration requirements clarified',
    ]),
    heading('Next Steps', 2),
    '1. Run discovery session\n2. Generate PRD\n3. Create solution design\n4. Begin development\n',
    horizontalRule(),
    `_Generated by pp-agency v${vars.version as string}_\n`,
  ].join('\n');

  return fm + body;
}

/**
 * Generate a Product Requirements Document (PRD).
 */
export function prdTemplate(config: ProjectConfig): string {
  const vars = buildTemplateData(config);

  const fm = frontmatter({
    title: `${config.name} — Product Requirements Document`,
    project: config.name,
    client: config.client,
    type: config.type,
    date: vars.date,
    version: config.version,
  });

  const body = [
    heading(`${config.name} — Product Requirements Document`, 1),
    heading('1. Executive Summary', 2),
    `This document outlines the product requirements for the ${config.name} project, a ${vars.projectTypeLabel as string} solution for ${vars.client as string}.\n`,
    heading('2. Business Context', 2),
    heading('2.1 Problem Statement', 3),
    '> Describe the business problem this project aims to solve.\n',
    heading('2.2 Business Goals', 3),
    checklist([
      'Increase operational efficiency',
      'Reduce manual data entry',
      'Improve data visibility and reporting',
      'Enhance user experience',
    ]),
    heading('3. User Personas', 2),
    table(
      ['Persona', 'Role', 'Goals', 'Pain Points'],
      [
        ['End User', 'Front-line worker', 'Complete tasks efficiently', 'Too many manual steps'],
        ['Manager', 'Team lead', 'Monitor team performance', 'Limited visibility'],
        ['Admin', 'System admin', 'Manage users and data', 'Complex configuration'],
      ]
    ),
    heading('4. Functional Requirements', 2),
    '| ID | Requirement | Priority | Status |',
    '| -- | ----------- | -------- | ------ |',
    '| FR-001 | Core data entry form | Must have | Planned |',
    '| FR-002 | Approval workflow | Must have | Planned |',
    '| FR-003 | Dashboard and reporting | Should have | Planned |',
    '| FR-004 | Mobile access | Should have | Planned |',
    '| FR-005 | Integration with external system | Could have | Planned |\n',
    heading('5. Non-Functional Requirements', 2),
    checklist([
      'Performance: Page load under 3 seconds',
      'Availability: 99.9% uptime SLA',
      'Security: Role-based access control',
      'Compliance: GDPR / industry regulations',
      'Scalability: Support up to 10,000 users',
    ]),
    heading('6. Data Requirements', 2),
    heading('6.1 Data Entities', 3),
    table(
      ['Entity', 'Description', 'Source'],
      [
        ['Account', 'Customer organization', 'Manual / CRM'],
        ['Contact', 'Individual contacts', 'Manual / CRM'],
        ['Case', 'Support cases', 'Application'],
      ]
    ),
    heading('6.2 Data Volume Estimates', 3),
    table(
      ['Entity', 'Initial Records', 'Monthly Growth'],
      [
        ['Account', '500', '50'],
        ['Contact', '2,000', '200'],
        ['Case', '10,000', '1,000'],
      ]
    ),
    heading('7. Integration Requirements', 2),
    '> Document all external system integrations.\n',
    heading('8. Acceptance Criteria', 2),
    checklist([
      'All must-have requirements implemented',
      'UAT completed with sign-off',
      'Performance benchmarks met',
      'Security review passed',
      'Documentation complete',
    ]),
    heading('9. Risks & Mitigations', 2),
    table(
      ['Risk', 'Impact', 'Likelihood', 'Mitigation'],
      [
        ['Scope creep', 'High', 'High', 'Strict change control process'],
        ['Integration complexity', 'High', 'Medium', 'Early prototyping'],
        ['User adoption', 'Medium', 'Medium', 'Change management plan'],
      ]
    ),
    heading('10. Timeline', 2),
    '| Phase | Duration | Deliverables |',
    '| ----- | -------- | ------------ |',
    '| Discovery | 1-2 weeks | Discovery report |',
    '| Design | 2-3 weeks | PRD + Solution design |',
    '| Build | 4-8 weeks | Configured solution |',
    '| Test | 2-3 weeks | Test report + UAT |',
    '| Deploy | 1-2 weeks | Production deployment |\n',
    horizontalRule(),
    `_Generated by pp-agency v${vars.version as string}_\n`,
  ].join('\n');

  return fm + body;
}

/**
 * Generate a Solution Design Document (SDD).
 */
export function solutionDesignTemplate(config: ProjectConfig): string {
  const vars = buildTemplateData(config);

  const fm = frontmatter({
    title: `${config.name} — Solution Design Document`,
    project: config.name,
    client: config.client,
    type: config.type,
    date: vars.date,
    version: config.version,
  });

  const body = [
    heading(`${config.name} — Solution Design Document`, 1),
    heading('1. Architecture Overview', 2),
    `This document defines the technical architecture for the ${config.name} ${vars.projectTypeLabel as string} solution.\n`,
    heading('1.1 High-Level Architecture', 3),
    codeBlock(
      `[User Layer]\n    |\n[Power Apps / Power Pages]\n    |\n[Dataverse]  <--->  [Power Automate]\n    |                      |\n[Azure Resources]  <-->  [External APIs]`,
      'text'
    ),
    heading('2. Data Model', 2),
    heading('2.1 Entity Relationship Diagram', 3),
    codeBlock(
      `[Account] 1:N [Contact]\n[Contact] 1:N [Case]\n[Case]    N:1 [Account]`,
      'text'
    ),
    heading('2.2 Entity Definitions', 3),
    table(
      ['Entity', 'Display Name', 'Purpose', 'Ownership'],
      [
        ['account', 'Account', 'Customer organizations', 'Organization'],
        ['contact', 'Contact', 'Individual people', 'Organization'],
        ['incident', 'Case', 'Support tickets', 'Organization'],
      ]
    ),
    heading('3. Security Model', 2),
    heading('3.1 Business Units', 3),
    '- Root business unit with department sub-units\n',
    heading('3.2 Security Roles', 3),
    table(
      ['Role', 'Access Level', 'Description'],
      [
        ['System Administrator', 'Organization', 'Full access to all data and settings'],
        ['Manager', 'Business Unit', 'Can view and edit all BU records'],
        ['User', 'User', 'Can only access own records'],
        ['Read-Only', 'None', 'View access only'],
      ]
    ),
    heading('3.3 Field-Level Security', 3),
    '> Document any fields requiring field-level security profiles.\n',
    heading('4. Application Design', 2),
    heading('4.1 App Structure', 3),
    checklist([
      'Navigation structure defined',
      'Form layouts designed',
      'View configurations specified',
      'Business rules documented',
      'Client-side scripting planned',
    ]),
    heading('4.2 Business Logic', 3),
    codeBlock(
      '// Example Power FX formula\nIf(\n  Status = "Approved",\n  Navigate(SuccessScreen),\n  Navigate(ErrorScreen)\n)',
      'javascript'
    ),
    heading('5. Automation & Workflows', 2),
    heading('5.1 Power Automate Flows', 3),
    table(
      ['Flow Name', 'Trigger', 'Actions', 'Error Handling'],
      [
        ['Approval Flow', 'Record created', 'Start approval, update status', 'Retry 3x, notify admin'],
        ['Notification Flow', 'Field changed', 'Send email', 'Log to Dataverse'],
      ]
    ),
    heading('5.2 Classic Workflows', 3),
    '> Document any classic workflows if required for real-time processing.\n',
    heading('6. Integration Design', 2),
    heading('6.1 Custom Connectors', 3),
    checklist([
      'Connector schema defined',
      'Authentication method selected',
      'Error handling strategy documented',
    ]),
    heading('6.2 API Endpoints', 3),
    table(
      ['Endpoint', 'Method', 'Purpose', 'Auth'],
      [
        ['/api/v1/customers', 'GET', 'List customers', 'OAuth 2.0'],
        ['/api/v1/cases', 'POST', 'Create case', 'OAuth 2.0'],
      ]
    ),
    heading('7. ALM Strategy', 2),
    heading('7.1 Environment Strategy', 3),
    table(
      ['Environment', 'Purpose', 'Type'],
      [
        ['DEV', 'Development and unit testing', 'Developer'],
        ['TEST', 'QA and UAT', 'Sandbox'],
        ['PROD', 'Production', 'Production'],
      ]
    ),
    heading('7.2 Solution Packaging', 3),
    checklist([
      'Managed solution for PROD',
      'Unmanaged solution for DEV',
      'Solution patches for hotfixes',
      'Versioning strategy defined',
    ]),
    heading('8. Monitoring & Diagnostics', 2),
    checklist([
      'Application Insights integration',
      'Error logging strategy',
      'Performance monitoring plan',
      'Health check procedures',
    ]),
    heading('9. Capacity Planning', 2),
    table(
      ['Resource', 'Estimated Usage', 'Limit'],
      [
        ['API Calls', '50,000/day', 'Based on license'],
        ['Database Storage', '5 GB', 'Expandable'],
        ['File Storage', '20 GB', 'Expandable'],
      ]
    ),
    horizontalRule(),
    `_Generated by pp-agency v${vars.version as string}_\n`,
  ].join('\n');

  return fm + body;
}

/**
 * Generate an agent task brief.
 */
export function agentBriefTemplate(
  config: ProjectConfig,
  agentType: AgentType,
  context?: string
): string {
  const vars = buildTemplateData(config);
  const agentLabel = getAgentTypeLabel(agentType);

  const fm = frontmatter({
    title: `${config.name} — ${agentLabel} Brief`,
    project: config.name,
    client: config.client,
    agent: agentType,
    date: vars.date,
    version: config.version,
  });

  const responsibilities: Record<AgentType, string[]> = {
    [AgentType.Architect]: [
      'Define overall solution architecture',
      'Create environment strategy',
      'Establish integration patterns',
      'Review and approve design decisions',
      'Ensure scalability and performance',
    ],
    [AgentType.DataModeler]: [
      'Design Dataverse data model',
      'Define entity relationships',
      'Create field specifications',
      'Plan data migration strategy',
      'Document data governance rules',
    ],
    [AgentType.Developer]: [
      'Configure Power Apps interfaces',
      'Build Power Automate flows',
      'Implement business logic',
      'Create custom connectors',
      'Write client-side scripts',
    ],
    [AgentType.Tester]: [
      'Create test plans and cases',
      'Execute functional testing',
      'Perform regression testing',
      'Document defects and resolutions',
      'Validate UAT scenarios',
    ],
    [AgentType.AlmEngineer]: [
      'Set up environment strategy',
      'Configure CI/CD pipelines',
      'Manage solution packaging',
      'Implement version control',
      'Monitor deployment health',
    ],
    [AgentType.SecurityAdmin]: [
      'Configure security roles',
      'Set up business units',
      'Implement field-level security',
      'Review audit logs',
      'Ensure compliance requirements',
    ],
  };

  const body = [
    heading(`${config.name} — ${agentLabel} Brief`, 1),
    heading('Agent Role', 2),
    `${bold('Type:')} ${agentLabel}\n`,
    `${bold('Project:')} ${config.name}\n`,
    `${bold('Client:')} ${config.client}\n`,
    heading('Responsibilities', 2),
    checklist(responsibilities[agentType] ?? ['Responsibilities to be defined']),
    heading('Context', 2),
    context ?? '> Project context to be added here.\n',
    heading('Deliverables', 2),
    checklist([
      'Design documents',
      'Configured components',
      'Test results',
      'Handover documentation',
    ]),
    heading('Constraints', 2),
    checklist([
      'Follow organizational naming conventions',
      'Adhere to security policies',
      'Document all customizations',
      'Ensure backward compatibility',
    ]),
    heading('Dependencies', 2),
    '- PRD: Link to product requirements\n- Solution Design: Link to architecture document\n- Environment Access: Required environments provisioned\n',
    horizontalRule(),
    `_Generated by pp-agency v${vars.version as string}_\n`,
  ].join('\n');

  return fm + body;
}

/**
 * Generate a checklist document.
 */
export function checklistTemplate(
  title: string,
  items: { category: string; tasks: string[] }[]
): string {
  const date = new Date().toISOString().split('T')[0];

  const fm = frontmatter({
    title: `${title} Checklist`,
    date,
    version: '1.0.0',
  });

  const bodyParts: string[] = [heading(`${title} Checklist`, 1)];

  for (const section of items) {
    bodyParts.push(heading(section.category, 2));
    bodyParts.push(checklist(section.tasks));
  }

  bodyParts.push(horizontalRule());
  bodyParts.push('_Generated by pp-agency_\n');

  return fm + bodyParts.join('\n');
}

/**
 * Generate a risk register document.
 */
export function riskRegisterTemplate(config: ProjectConfig): string {
  const vars = buildTemplateData(config);

  const fm = frontmatter({
    title: `${config.name} — Risk Register`,
    project: config.name,
    client: config.client,
    date: vars.date,
    version: config.version,
  });

  const body = [
    heading(`${config.name} — Risk Register`, 1),
    heading('Identified Risks', 2),
    table(
      ['ID', 'Risk', 'Impact', 'Likelihood', 'Mitigation', 'Owner'],
      [
        ['R-001', 'Scope creep', 'High', 'High', 'Change control board', 'Project Manager'],
        ['R-002', 'Technical complexity', 'High', 'Medium', 'Proof of concepts', 'Architect'],
        ['R-003', 'Resource availability', 'Medium', 'Medium', 'Resource buffer', 'Manager'],
        ['R-004', 'Integration failure', 'High', 'Low', 'Early integration testing', 'Developer'],
        ['R-005', 'User adoption', 'Medium', 'Medium', 'Change management', 'Business Analyst'],
      ]
    ),
    heading('Risk Scoring Matrix', 2),
    codeBlock(
      `Impact    | Low(1) | Med(2) | High(3)\n----------|--------|--------|-------\nLow(1)    |   1    |   2    |   3\nMed(2)    |   2    |   4    |   6\nHigh(3)   |   3    |   6    |   9\n\nScore >= 6 = Critical risk requiring immediate attention`,
      'text'
    ),
    heading('Mitigation Status', 2),
    checklist([
      'Risk R-001: Change control process defined',
      'Risk R-002: POCs scheduled for sprint 1',
      'Risk R-003: Backup resources identified',
      'Risk R-004: Integration test plan created',
      'Risk R-005: Change management plan drafted',
    ]),
    horizontalRule(),
    `_Generated by pp-agency v${vars.version as string}_\n`,
  ].join('\n');

  return fm + body;
}

/**
 * Generate a discovery report template.
 */
export function discoveryReportTemplate(
  client: string,
  projectType: ProjectType,
  tools: string[],
  timeline: string,
  budget: string,
  scores: { category: string; score: number; notes: string }[]
): string {
  const date = new Date().toISOString().split('T')[0];

  const fm = frontmatter({
    title: `${client} — Discovery Report`,
    client,
    type: projectType,
    date,
    version: '1.0.0',
  });

  const avgScore = scores.length > 0
    ? (scores.reduce((sum, s) => sum + s.score, 0) / scores.length).toFixed(1)
    : '0';

  const body = [
    heading(`${client} — Discovery Report`, 1),
    heading('Executive Summary', 2),
    `Discovery session completed for ${client}. Overall readiness score: **${avgScore}/10**.\n`,
    heading('Client Profile', 2),
    `- **Client:** ${client}`,
    `- **Project Type:** ${projectType}`,
    `- **Timeline:** ${timeline}`,
    `- **Budget Range:** ${budget}\n`,
    heading('Scoring Matrix', 2),
    table(
      ['Category', 'Score (1-10)', 'Notes'],
      scores.map((s) => [s.category, String(s.score), s.notes])
    ),
    heading('Tools & Technologies', 2),
    tools.length > 0 ? tools.map((t) => `- ${t}`).join('\n') + '\n' : '> To be determined.\n',
    heading('Recommendations', 2),
    checklist([
      'Confirm licensing requirements with Microsoft partner',
      'Set up development environments early',
      'Establish governance framework before build',
      'Plan for iterative user feedback cycles',
    ]),
    heading('Identified Risks', 2),
    checklist([
      'Scope not fully defined — needs follow-up workshop',
      'Integration points require technical validation',
      'Change management may impact timeline',
    ]),
    heading('Next Steps', 2),
    '1. Finalize project scope document\n2. Generate PRD\n3. Begin solution design phase\n4. Provision environments\n',
    horizontalRule(),
    '_Generated by pp-agency_\n',
  ].join('\n');

  return fm + body;
}

/**
 * Generate a licensing estimate document.
 */
export function licensingEstimateTemplate(
  currency: string,
  components: { name: string; quantity: number; unitPrice: number; total: number }[],
  monthlyTotal: number,
  annualTotal: number
): string {
  const date = new Date().toISOString().split('T')[0];
  const currencySymbol = currency === 'gbp' ? '£' : currency === 'eur' ? '€' : '$';

  const fm = frontmatter({
    title: 'Power Platform Licensing Estimate',
    date,
    currency,
    version: '1.0.0',
  });

  const body = [
    heading('Power Platform Licensing Estimate', 1),
    heading('Component Breakdown', 2),
    table(
      ['Component', 'Quantity', `Unit Price (${currencySymbol})`, `Total (${currencySymbol})`],
      components.map((c) => [
        c.name,
        String(c.quantity),
        `${currencySymbol}${c.unitPrice.toFixed(2)}`,
        `${currencySymbol}${c.total.toFixed(2)}`,
      ])
    ),
    heading('Summary', 2),
    `- **Monthly Total:** ${currencySymbol}${monthlyTotal.toFixed(2)}`,
    `- **Annual Total:** ${currencySymbol}${annualTotal.toFixed(2)}\n`,
    heading('Notes', 2),
    '> Prices are estimates based on current Microsoft pricing. Actual costs may vary based on',
    '> region, volume discounts, and licensing agreements. Contact a Microsoft partner for',
    '> formal pricing.\n',
    heading('Recommendations', 2),
    checklist([
      'Review licensing with Microsoft partner for volume discounts',
      'Consider Power Apps per-app plans for infrequent users',
      'Evaluate pay-as-you-go for variable workloads',
      'Plan for seasonal usage spikes',
    ]),
    horizontalRule(),
    '_Generated by pp-agency_\n',
  ].join('\n');

  return fm + body;
}
