import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {
  projectBriefTemplate,
  prdTemplate,
  solutionDesignTemplate,
  agentBriefTemplate,
  checklistTemplate,
  riskRegisterTemplate,
  discoveryReportTemplate,
  licensingEstimateTemplate,
  getProjectTypeLabel,
  getAgentTypeLabel,
} from '../src/lib/templates.js';
import {
  ProjectType,
  AgentType,
  type ProjectConfig,
} from '../src/lib/project-types.js';

// ---------------------------------------------------------------------------
// Shared, deterministic fixtures
// ---------------------------------------------------------------------------

const PROJECT_NAME = 'Contoso CRM';
const CLIENT_NAME = 'Contoso Inc.';

/** A realistic, fully-populated ProjectConfig used across the suite. */
const config: ProjectConfig = {
  name: PROJECT_NAME,
  type: ProjectType.ModelDriven,
  client: CLIENT_NAME,
  description: 'A model-driven CRM for sales operations.',
  createdAt: '2026-01-15',
  version: '1.0.0',
};

/**
 * Assert that a generated document is a non-empty markdown string that carries
 * the project + client name into both the frontmatter and the body footer.
 */
function assertProjectDoc(doc: string): void {
  assert.equal(typeof doc, 'string');
  assert.ok(doc.length > 0, 'document should not be empty');
  // Frontmatter block is present and opens the document.
  assert.ok(doc.startsWith('---\n'), 'document should start with frontmatter');
  // Injected project + client names appear in the rendered output.
  assert.ok(doc.includes(PROJECT_NAME), 'document should contain the project name');
  assert.ok(doc.includes(CLIENT_NAME), 'document should contain the client name');
  // Shared footer marker emitted by the template builders.
  assert.ok(doc.includes('_Generated by pp-agency'), 'document should contain the footer');
}

// ---------------------------------------------------------------------------
// projectBriefTemplate
// ---------------------------------------------------------------------------

test('projectBriefTemplate: contains brief headings and the injected names', () => {
  const doc = projectBriefTemplate(config);
  assertProjectDoc(doc);

  assert.ok(doc.includes(`# ${PROJECT_NAME} — Project Brief`), 'has H1 brief title');
  assert.ok(doc.includes('## Overview'), 'has Overview section');
  assert.ok(doc.includes('## Client'), 'has Client section');
  assert.ok(doc.includes('## Scope'), 'has Scope section');
  assert.ok(doc.includes('## Objectives'), 'has Objectives section');
  assert.ok(doc.includes('## Deliverables'), 'has Deliverables section');
  assert.ok(doc.includes('## Next Steps'), 'has Next Steps section');
  // Human-readable project type label is rendered (not the raw enum value).
  assert.ok(doc.includes('Model-Driven App'), 'renders the project type label');
});

// ---------------------------------------------------------------------------
// prdTemplate
// ---------------------------------------------------------------------------

test('prdTemplate: contains the numbered PRD sections and the injected names', () => {
  const doc = prdTemplate(config);
  assertProjectDoc(doc);

  assert.ok(
    doc.includes(`# ${PROJECT_NAME} — Product Requirements Document`),
    'has H1 PRD title',
  );
  assert.ok(doc.includes('## 1. Executive Summary'), 'has Executive Summary');
  assert.ok(doc.includes('## 2. Business Context'), 'has Business Context');
  assert.ok(doc.includes('## 3. User Personas'), 'has User Personas');
  assert.ok(doc.includes('## 4. Functional Requirements'), 'has Functional Requirements');
  assert.ok(
    doc.includes('## 5. Non-Functional Requirements'),
    'has Non-Functional Requirements',
  );
  assert.ok(doc.includes('## 8. Acceptance Criteria'), 'has Acceptance Criteria');
  assert.ok(doc.includes('## 10. Timeline'), 'has Timeline');
  // A representative functional-requirement row is present.
  assert.ok(doc.includes('FR-001'), 'has a functional requirement id');
});

// ---------------------------------------------------------------------------
// solutionDesignTemplate
// ---------------------------------------------------------------------------

test('solutionDesignTemplate: contains the architecture sections and injected names', () => {
  const doc = solutionDesignTemplate(config);
  assertProjectDoc(doc);

  assert.ok(
    doc.includes(`# ${PROJECT_NAME} — Solution Design Document`),
    'has H1 SDD title',
  );
  assert.ok(doc.includes('## 1. Architecture Overview'), 'has Architecture Overview');
  assert.ok(doc.includes('## 2. Data Model'), 'has Data Model');
  assert.ok(doc.includes('## 3. Security Model'), 'has Security Model');
  assert.ok(doc.includes('## 7. ALM Strategy'), 'has ALM Strategy');
  assert.ok(doc.includes('## 9. Capacity Planning'), 'has Capacity Planning');
  // A fenced code block is emitted for the architecture diagram.
  assert.ok(doc.includes('```text'), 'has a fenced text code block');
});

// ---------------------------------------------------------------------------
// agentBriefTemplate
// ---------------------------------------------------------------------------

test('agentBriefTemplate: renders the agent label, sections, and injected context', () => {
  const customContext = '> This engagement focuses on the sales pipeline migration.\n';
  const doc = agentBriefTemplate(config, AgentType.Architect, customContext);
  assertProjectDoc(doc);

  const label = getAgentTypeLabel(AgentType.Architect);
  assert.equal(label, 'Solution Architect');
  assert.ok(doc.includes(`# ${PROJECT_NAME} — ${label} Brief`), 'has H1 agent-brief title');
  assert.ok(doc.includes('## Agent Role'), 'has Agent Role section');
  assert.ok(doc.includes('## Responsibilities'), 'has Responsibilities section');
  assert.ok(doc.includes('## Context'), 'has Context section');
  assert.ok(doc.includes('## Deliverables'), 'has Deliverables section');
  // The supplied context is injected verbatim into the body.
  assert.ok(doc.includes(customContext.trim()), 'injects the supplied context');
  // Architect-specific responsibility is present.
  assert.ok(
    doc.includes('Define overall solution architecture'),
    'has an architect responsibility',
  );
});

test('agentBriefTemplate: falls back to placeholder context when none is supplied', () => {
  const doc = agentBriefTemplate(config, AgentType.Tester);
  assertProjectDoc(doc);

  assert.ok(doc.includes(`${getAgentTypeLabel(AgentType.Tester)} Brief`), 'has tester title');
  assert.ok(
    doc.includes('> Project context to be added here.'),
    'uses the default context placeholder',
  );
  // Tester-specific responsibility is present.
  assert.ok(doc.includes('Create test plans and cases'), 'has a tester responsibility');
});

test('agentBriefTemplate: produces a brief for every AgentType', () => {
  for (const agentType of Object.values(AgentType)) {
    const doc = agentBriefTemplate(config, agentType);
    assertProjectDoc(doc);
    const label = getAgentTypeLabel(agentType);
    assert.notEqual(label, 'Unknown Agent', `${agentType} should have a known label`);
    assert.ok(doc.includes(`${label} Brief`), `${agentType} brief carries its label`);
  }
});

// ---------------------------------------------------------------------------
// checklistTemplate
// ---------------------------------------------------------------------------

test('checklistTemplate: renders the title, categories, and task items', () => {
  const doc = checklistTemplate('Deployment', [
    { category: 'Pre-Deployment', tasks: ['Backup the environment', 'Notify stakeholders'] },
    { category: 'Go-Live', tasks: ['Import managed solution', 'Smoke test'] },
  ]);

  assert.ok(doc.startsWith('---\n'), 'has frontmatter');
  assert.ok(doc.includes('# Deployment Checklist'), 'has H1 checklist title');
  assert.ok(doc.includes('## Pre-Deployment'), 'has the first category heading');
  assert.ok(doc.includes('## Go-Live'), 'has the second category heading');
  assert.ok(doc.includes('- [ ] Backup the environment'), 'renders a task as a checkbox item');
  assert.ok(doc.includes('- [ ] Smoke test'), 'renders the final task as a checkbox item');
  assert.ok(doc.includes('_Generated by pp-agency'), 'has the footer');
});

// ---------------------------------------------------------------------------
// riskRegisterTemplate
// ---------------------------------------------------------------------------

test('riskRegisterTemplate: contains the risk sections and injected names', () => {
  const doc = riskRegisterTemplate(config);
  assertProjectDoc(doc);

  assert.ok(doc.includes(`# ${PROJECT_NAME} — Risk Register`), 'has H1 risk-register title');
  assert.ok(doc.includes('## Identified Risks'), 'has Identified Risks section');
  assert.ok(doc.includes('## Risk Scoring Matrix'), 'has Risk Scoring Matrix section');
  assert.ok(doc.includes('## Mitigation Status'), 'has Mitigation Status section');
  assert.ok(doc.includes('R-001'), 'has a risk id row');
});

// ---------------------------------------------------------------------------
// discoveryReportTemplate
// ---------------------------------------------------------------------------

test('discoveryReportTemplate: renders the client, scores, and recommendations', () => {
  const doc = discoveryReportTemplate(
    CLIENT_NAME,
    ProjectType.Integration,
    ['Power Automate', 'Custom Connector'],
    '8-12 weeks',
    '£50k-£80k',
    [
      { category: 'Data Readiness', score: 7, notes: 'Sources identified' },
      { category: 'Governance', score: 5, notes: 'DLP policy pending' },
    ],
  );

  assert.ok(doc.startsWith('---\n'), 'has frontmatter');
  assert.ok(doc.includes(CLIENT_NAME), 'contains the client name');
  assert.ok(doc.includes(`# ${CLIENT_NAME} — Discovery Report`), 'has H1 discovery title');
  assert.ok(doc.includes('## Executive Summary'), 'has Executive Summary section');
  assert.ok(doc.includes('## Scoring Matrix'), 'has Scoring Matrix section');
  assert.ok(doc.includes('## Tools & Technologies'), 'has Tools section');
  // Average of 7 and 5 is 6.0 — deterministic from the supplied scores.
  assert.ok(doc.includes('6.0/10'), 'computes the average readiness score');
  assert.ok(doc.includes('Power Automate'), 'lists a supplied tool');
  assert.ok(doc.includes('Data Readiness'), 'renders a supplied score category');
});

// ---------------------------------------------------------------------------
// licensingEstimateTemplate
// ---------------------------------------------------------------------------

test('licensingEstimateTemplate: renders currency-formatted totals and components', () => {
  const doc = licensingEstimateTemplate(
    'gbp',
    [
      { name: 'Power Apps Per User', quantity: 25, unitPrice: 15.4, total: 385.0 },
      { name: 'Dataverse Capacity', quantity: 1, unitPrice: 40.0, total: 40.0 },
    ],
    425.0,
    5100.0,
  );

  assert.ok(doc.startsWith('---\n'), 'has frontmatter');
  assert.ok(doc.includes('# Power Platform Licensing Estimate'), 'has H1 licensing title');
  assert.ok(doc.includes('## Component Breakdown'), 'has Component Breakdown section');
  assert.ok(doc.includes('## Summary'), 'has Summary section');
  // GBP currency symbol is used and totals are formatted to two decimals.
  assert.ok(doc.includes('£385.00'), 'formats a component total in GBP');
  assert.ok(doc.includes('£425.00'), 'formats the monthly total in GBP');
  assert.ok(doc.includes('£5100.00'), 'formats the annual total in GBP');
  assert.ok(doc.includes('Power Apps Per User'), 'lists a supplied component');
});

// ---------------------------------------------------------------------------
// label helpers
// ---------------------------------------------------------------------------

test('getProjectTypeLabel: maps every ProjectType to a human-readable label', () => {
  for (const type of Object.values(ProjectType)) {
    const label = getProjectTypeLabel(type);
    assert.equal(typeof label, 'string');
    assert.ok(label.length > 0, `${type} should map to a non-empty label`);
    assert.notEqual(label, 'Unknown', `${type} should not map to the fallback label`);
  }
});

// ---------------------------------------------------------------------------
// Filesystem round-trip: write a generated doc to a temp dir, then clean up.
// ---------------------------------------------------------------------------

test('generated documents survive a filesystem write/read round-trip', () => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'pp-agency-templates-'));
  try {
    const cases: Array<[string, string]> = [
      ['project-brief.md', projectBriefTemplate(config)],
      ['prd.md', prdTemplate(config)],
      ['solution-design.md', solutionDesignTemplate(config)],
      ['architect-brief.md', agentBriefTemplate(config, AgentType.Architect)],
    ];

    for (const [fileName, contents] of cases) {
      const filePath = path.join(tmpDir, fileName);
      fs.writeFileSync(filePath, contents, 'utf8');
      const readBack = fs.readFileSync(filePath, 'utf8');
      assert.equal(readBack, contents, `${fileName} round-trips unchanged`);
      assert.ok(readBack.includes(PROJECT_NAME), `${fileName} retains the project name`);
    }
  } finally {
    // Always clean up the temp directory, even if an assertion above fails.
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
});
